export const SESSION_EXPIRED = 'SESSION_EXPIRED';
export const AUTH_SESSION_TIMEOUT_STATUSES = 'AUTH_SESSION_TIMEOUT_STATUSES';
export const INSUFFICIENT_PERMISSION = 'INSUFFICIENT_PERMISSION';
export const FORBIDDEN_STATUS_CODE = 'FORBIDDEN_STATUS_CODE';
export const IDTOKEN_DEFAULT_VALUE = 'IDTOKEN_DEFAULT_VALUE';

export const AUTH_SESSION_TIMEOUT_STATUSES = [498, 401];
